//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenSlate.Database
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ToDo
    {      
        public int Id { get; set; }
        [Required]
        [StringLength(10)]
        public string Title { get; set; }
        public int Estimated_Hours { get; set; }
        public string Created_By { get; set; }
        public bool Completed { get; set; }
    }
}
